- name: install and run nginx
  hosts: web
  become: yes # -b
  tasks: # task=module=collection
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      status: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
