- name: install packages
  hosts: web
  become: yes
  tasks: 
  - name: install packages
    ansible.builtin.package:
      name:
      status: installed
    loop: "{{ item }}"
    - gcc
    - mysql
    - git
    - zip
