- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0f295dba688833f42
    sg_id: sg-0a1f6a3c9827a2db2
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install AWS Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}" 